version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Using port 5001 on host to avoid conflicts
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - MODEL_DIR=/app/models
      - DB_PATH=/app/data/images.db
    command: python app.py
    # Removed GPU requirements

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    command: npm start